# Generated by Django 4.2.8 on 2026-01-12 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('missao', models.TextField(verbose_name='Missão')),
                ('visao', models.TextField(blank=True, verbose_name='Visão')),
                ('valores', models.TextField(verbose_name='Valores')),
                ('historia', models.TextField(blank=True, verbose_name='História')),
                ('publico_externo', models.TextField(verbose_name='Público Externo')),
                ('publico_interno', models.TextField(blank=True, verbose_name='Público Interno')),
                ('segmentos_internos', models.JSONField(blank=True, default=list, help_text='Lista de segmentos: ["Gestores", "Operacional", etc]', verbose_name='Segmentos Internos')),
                ('posicionamento', models.TextField(verbose_name='Posicionamento de Marca')),
                ('diferenciais', models.TextField(verbose_name='Diferenciais Competitivos')),
                ('proposta_valor', models.TextField(blank=True, verbose_name='Proposta de Valor')),
                ('tom_voz_externo', models.TextField(verbose_name='Tom de Voz Externo')),
                ('tom_voz_interno', models.TextField(blank=True, verbose_name='Tom de Voz Interno')),
                ('palavras_recomendadas', models.JSONField(default=list, help_text='Lista de palavras-chave da marca', verbose_name='Palavras Recomendadas')),
                ('palavras_evitar', models.JSONField(default=list, help_text='Lista de palavras que não devem ser usadas', verbose_name='Palavras a Evitar')),
                ('paleta_cores', models.JSONField(default=dict, help_text='{"primaria": "#hex", "secundaria": "#hex", "destaque": "#hex"}', verbose_name='Paleta de Cores')),
                ('tipografia', models.JSONField(default=dict, help_text='{"titulo": "Font Name", "corpo": "Font Name", "destaque": "Font Name"}', verbose_name='Tipografia')),
                ('site_institucional', models.URLField(blank=True, verbose_name='Site Institucional')),
                ('redes_sociais', models.JSONField(default=dict, help_text='{"instagram": "url", "linkedin": "url", "facebook": "url", etc}', verbose_name='Redes Sociais')),
                ('templates_redes', models.JSONField(blank=True, default=dict, help_text='Configurações específicas por rede social', verbose_name='Templates por Rede Social')),
                ('fontes_confiaveis', models.JSONField(default=list, help_text='Lista de URLs de pesquisas confiáveis', verbose_name='Fontes Confiáveis')),
                ('canais_trends', models.JSONField(blank=True, default=list, help_text='Canais customizados para monitoramento', verbose_name='Canais de Trends')),
                ('palavras_chave_trends', models.JSONField(blank=True, default=list, help_text='Termos para monitoramento automático', verbose_name='Palavras-chave para Trends')),
                ('completude_percentual', models.IntegerField(default=0, help_text='Calculado automaticamente', verbose_name='Completude (%)')),
                ('is_complete', models.BooleanField(default=False, help_text='Indica se atende requisitos mínimos', verbose_name='Base Completa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_updates', to=settings.AUTH_USER_MODEL, verbose_name='Última atualização por')),
            ],
            options={
                'verbose_name': 'Base de Conhecimento',
                'verbose_name_plural': 'Bases de Conhecimento',
            },
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('s3_key', models.CharField(max_length=500, verbose_name='Chave S3')),
                ('s3_url', models.URLField(max_length=1000, verbose_name='URL S3')),
                ('perceptual_hash', models.CharField(help_text='Para evitar imagens similares', max_length=64, verbose_name='Hash Perceptual')),
                ('file_size', models.BigIntegerField(verbose_name='Tamanho (bytes)')),
                ('width', models.IntegerField(verbose_name='Largura')),
                ('height', models.IntegerField(verbose_name='Altura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='knowledge.knowledgebase', verbose_name='Base de Conhecimento')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Imagem de Referência',
                'verbose_name_plural': 'Imagens de Referência',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('logo_type', models.CharField(choices=[('principal', 'Principal'), ('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('icone', 'Ícone'), ('monocromatico', 'Monocromático')], max_length=20, verbose_name='Tipo')),
                ('s3_key', models.CharField(max_length=500, verbose_name='Chave S3')),
                ('s3_url', models.URLField(max_length=1000, verbose_name='URL S3')),
                ('file_format', models.CharField(max_length=10, verbose_name='Formato')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Logo Principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='knowledge.knowledgebase', verbose_name='Base de Conhecimento')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
                'ordering': ['-is_primary', 'logo_type'],
            },
        ),
        migrations.CreateModel(
            name='CustomFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Fonte')),
                ('font_type', models.CharField(choices=[('titulo', 'Título'), ('corpo', 'Corpo'), ('destaque', 'Destaque')], max_length=20, verbose_name='Tipo')),
                ('s3_key', models.CharField(max_length=500, verbose_name='Chave S3')),
                ('s3_url', models.URLField(max_length=1000, verbose_name='URL S3')),
                ('file_format', models.CharField(choices=[('ttf', 'TrueType'), ('otf', 'OpenType'), ('woff', 'WOFF'), ('woff2', 'WOFF2')], max_length=10, verbose_name='Formato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fonts', to='knowledge.knowledgebase', verbose_name='Base de Conhecimento')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Fonte Customizada',
                'verbose_name_plural': 'Fontes Customizadas',
                'ordering': ['font_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('social_media', models.JSONField(blank=True, default=dict, verbose_name='Redes Sociais')),
                ('strengths', models.TextField(blank=True, verbose_name='Pontos Fortes')),
                ('weaknesses', models.TextField(blank=True, verbose_name='Pontos Fracos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='knowledge.knowledgebase', verbose_name='Base de Conhecimento')),
            ],
            options={
                'verbose_name': 'Concorrente',
                'verbose_name_plural': 'Concorrentes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(help_text='Nome do bloco alterado', max_length=50, verbose_name='Bloco')),
                ('field_name', models.CharField(max_length=100, verbose_name='Campo')),
                ('old_value', models.TextField(blank=True, verbose_name='Valor Anterior')),
                ('new_value', models.TextField(verbose_name='Novo Valor')),
                ('change_summary', models.CharField(max_length=500, verbose_name='Resumo da Alteração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='knowledge.knowledgebase', verbose_name='Base de Conhecimento')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Alteração',
                'verbose_name_plural': 'Logs de Alterações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='knowledge_k_created_2529d7_idx'), models.Index(fields=['knowledge_base', '-created_at'], name='knowledge_k_knowled_fc106c_idx')],
            },
        ),
    ]
