# Generated by Django 4.2.8 on 2026-01-13 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('network_type', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('twitter', 'Twitter/X'), ('other', 'Outro')], max_length=20, verbose_name='Tipo de Rede')),
                ('url', models.URLField(verbose_name='URL')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='knowledge.knowledgebase', verbose_name='Base de Conhecimento')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialNetworkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Template')),
                ('width', models.IntegerField(verbose_name='Largura (px)')),
                ('height', models.IntegerField(verbose_name='Altura (px)')),
                ('aspect_ratio', models.CharField(help_text='Ex: 1:1, 9:16, 16:9', max_length=10, verbose_name='Aspect Ratio')),
                ('character_limit', models.IntegerField(blank=True, null=True, verbose_name='Limite de Caracteres')),
                ('hashtag_limit', models.IntegerField(blank=True, null=True, verbose_name='Limite de Hashtags')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='knowledge.socialnetwork', verbose_name='Rede Social')),
            ],
            options={
                'verbose_name': 'Template de Rede Social',
                'verbose_name_plural': 'Templates de Redes Sociais',
                'ordering': ['social_network', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Cor')),
                ('hex_code', models.CharField(help_text='Formato: #RRGGBB', max_length=7, verbose_name='Código HEX')),
                ('color_type', models.CharField(choices=[('primary', 'Primária'), ('secondary', 'Secundária'), ('accent', 'Acento')], max_length=20, verbose_name='Tipo')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='knowledge.knowledgebase', verbose_name='Base de Conhecimento')),
            ],
            options={
                'verbose_name': 'Cor da Paleta',
                'verbose_name_plural': 'Cores da Paleta',
                'ordering': ['order', 'name'],
                'unique_together': {('knowledge_base', 'name')},
            },
        ),
    ]
