# Generated by Django 4.2.8 on 2026-01-13 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0002_socialnetwork_socialnetworktemplate_colorpalette'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Marketing, Operacional, Médicos', max_length=100, verbose_name='Nome')),
                ('code', models.SlugField(help_text='Gerado automaticamente a partir do nome', max_length=100, verbose_name='Código')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do segmento', verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição', verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para desativar sem excluir', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_segments', to='knowledge.knowledgebase', verbose_name='Base de Conhecimento')),
                ('parent', models.ForeignKey(blank=True, help_text='Para criar hierarquia (ex: Marketing > Digital)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='knowledge.internalsegment', verbose_name='Segmento Pai')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Segmento Interno',
                'verbose_name_plural': 'Segmentos Internos',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['knowledge_base', 'is_active'], name='knowledge_i_knowled_9ce562_idx'), models.Index(fields=['parent'], name='knowledge_i_parent__b04256_idx')],
                'unique_together': {('knowledge_base', 'code')},
            },
        ),
    ]
