# Generated by Django 4.2.8 on 2026-01-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_internalsegment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='fontes_confiaveis',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs de pesquisas confiáveis', verbose_name='Fontes Confiáveis'),
        ),
    ]
