# Generated by Django 4.2.8 on 2026-01-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_make_fontes_confiaveis_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='paleta_cores',
            field=models.JSONField(blank=True, default=dict, help_text='⚠️ DEPRECADO: Use ColorPalette model. Este campo será removido em versão futura.', verbose_name='Paleta de Cores (LEGADO)'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='redes_sociais',
            field=models.JSONField(blank=True, default=dict, help_text='⚠️ DEPRECADO: Use SocialNetwork model. Este campo será removido em versão futura.', verbose_name='Redes Sociais (LEGADO)'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='tipografia',
            field=models.JSONField(blank=True, default=dict, help_text='⚠️ DEPRECADO: Use CustomFont model. Este campo será removido em versão futura.', verbose_name='Tipografia (LEGADO)'),
        ),
    ]
