# Generated by Django 4.2.8 on 2026-01-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_deprecate_json_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='palavras_evitar',
            field=models.JSONField(blank=True, default=list, help_text='Lista de palavras que não devem ser usadas', verbose_name='Palavras a Evitar'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='palavras_recomendadas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de palavras-chave da marca', verbose_name='Palavras Recomendadas'),
        ),
    ]
