# Generated by Django 4.2.8 on 2026-01-21 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_pautaauditlog_alter_area_name_and_more'),
        ('knowledge', '0006_fix_optional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organização à qual esta base de conhecimento pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='core.organization', verbose_name='Organização'),
        ),
    ]
