# Generated by Django 4.2.8 on 2026-01-27 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0007_knowledgebase_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfont',
            name='file_format',
            field=models.CharField(choices=[('ttf', 'TrueType (TTF)'), ('otf', 'OpenType (OTF)'), ('woff', 'WOFF'), ('woff2', 'WOFF2')], help_text='Formato do arquivo de fonte', max_length=10, verbose_name='Formato'),
        ),
        migrations.CreateModel(
            name='Typography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(help_text='Ex: Texto corrido, Títulos, Botões, etc', max_length=50, verbose_name='Uso da Fonte')),
                ('font_source', models.CharField(choices=[('google', 'Google Fonts'), ('upload', 'Upload TTF/OTF')], max_length=20, verbose_name='Origem da Fonte')),
                ('google_font_name', models.CharField(blank=True, help_text='Ex: Montserrat, Open Sans, Roboto', max_length=200, verbose_name='Nome da Fonte (Google)')),
                ('google_font_weight', models.CharField(blank=True, help_text='Ex: Regular, Bold, Light, 400, 700', max_length=20, verbose_name='Peso da Fonte')),
                ('google_font_url', models.URLField(blank=True, help_text='Gerado automaticamente', verbose_name='URL Google Fonts')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('custom_font', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typography_usages', to='knowledge.customfont', verbose_name='Fonte Customizada')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typography_settings', to='knowledge.knowledgebase', verbose_name='Base de Conhecimento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração de Tipografia',
                'verbose_name_plural': 'Configurações de Tipografia',
                'ordering': ['order', 'usage'],
                'unique_together': {('knowledge_base', 'usage')},
            },
        ),
    ]
