# Generated by Django 4.2.8 on 2026-01-27 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_add_typography_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebase',
            name='paleta_cores',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='redes_sociais',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='tipografia',
        ),
    ]
