# Generated by Django 4.2.8 on 2026-01-28 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0010_add_database_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='colorpalette',
            name='color_kb_idx',
        ),
        migrations.RemoveIndex(
            model_name='colorpalette',
            name='color_kb_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='customfont',
            name='font_kb_idx',
        ),
        migrations.RemoveIndex(
            model_name='customfont',
            name='font_kb_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='internalsegment',
            name='segment_kb_idx',
        ),
        migrations.RemoveIndex(
            model_name='internalsegment',
            name='segment_kb_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='logo',
            name='logo_kb_idx',
        ),
        migrations.RemoveIndex(
            model_name='logo',
            name='logo_kb_primary_idx',
        ),
        migrations.RemoveIndex(
            model_name='logo',
            name='logo_kb_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='referenceimage',
            name='refimg_kb_idx',
        ),
        migrations.RemoveIndex(
            model_name='referenceimage',
            name='refimg_kb_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='socialnetwork',
            name='social_kb_idx',
        ),
        migrations.RemoveIndex(
            model_name='typography',
            name='typo_kb_idx',
        ),
        migrations.RemoveIndex(
            model_name='typography',
            name='typo_kb_usage_idx',
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='True quando usuário clica em "Salvar Base IAMKT" pela primeira vez e envia dados para N8N', verbose_name='Onboarding Concluído'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp de quando o onboarding foi concluído', null=True, verbose_name='Data de Conclusão do Onboarding'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='onboarding_completed_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que completou o onboarding pela primeira vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_completions', to=settings.AUTH_USER_MODEL, verbose_name='Onboarding Concluído Por'),
        ),
    ]
