# Generated by Django 4.2.8 on 2026-01-29 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0014_add_n8n_analysis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='suggestions_reviewed',
            field=models.BooleanField(default=False, help_text='True quando usuário clica em "Aplicar Sugestões Selecionadas" pela primeira vez', verbose_name='Sugestões Revisadas'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='suggestions_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp de quando as sugestões foram revisadas', null=True, verbose_name='Data de Revisão das Sugestões'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='suggestions_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que revisou as sugestões pela primeira vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Sugestões Revisadas Por'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='descricao_produto',
            field=models.TextField(blank=True, verbose_name='Descrição do Produto/Serviço'),
        ),
    ]
