# Generated by Django 4.2.8 on 2026-02-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0015_add_suggestions_reviewed_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='compilation_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Completa'), ('error', 'Erro')], default='pending', max_length=20, verbose_name='Status da Compilação'),
        ),
    ]
