# Generated by Django 4.2.8 on 2026-02-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0016_add_compilation_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='accepted_suggestion_fields',
            field=models.JSONField(blank=True, default=list, help_text='Lista de nomes de campos que tiveram sugestões aceitas (para reavaliação)', verbose_name='Campos com Sugestões Aceitas'),
        ),
    ]
