# Generated by Django 4.2.8 on 2026-02-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0017_add_accepted_suggestion_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='descricao_produto',
            field=models.TextField(verbose_name='Descrição do Produto/Serviço'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='diferenciais',
            field=models.TextField(blank=True, verbose_name='Diferenciais Competitivos'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='missao',
            field=models.TextField(blank=True, verbose_name='Missão'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='posicionamento',
            field=models.TextField(blank=True, verbose_name='Posicionamento de Marca'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='publico_externo',
            field=models.TextField(blank=True, verbose_name='Público Externo'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='tom_voz_externo',
            field=models.TextField(blank=True, verbose_name='Tom de Voz Externo'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='valores',
            field=models.TextField(blank=True, verbose_name='Valores'),
        ),
    ]
