# Generated by Django 4.2.8 on 2026-02-02 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_organization_email_marketing_enabled_and_more'),
        ('pautas', '0002_alter_pauta_rede_social'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_theme', models.TextField(blank=True, help_text='Tema solicitado pelo usuário para geração do post', verbose_name='Tema Solicitado')),
                ('title', models.CharField(blank=True, help_text='Título do post (se aplicável)', max_length=220, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, help_text='Subtítulo do post (se aplicável)', max_length=220, verbose_name='Subtítulo')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('carrossel', 'Carrossel'), ('story', 'Story'), ('reels', 'Reels')], max_length=20, verbose_name='Tipo')),
                ('social_network', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('tiktok', 'TikTok')], max_length=20, verbose_name='Rede Social')),
                ('ia_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini')], max_length=20, verbose_name='Provider IA')),
                ('ia_model_text', models.CharField(max_length=50, verbose_name='Modelo IA Texto')),
                ('ia_model_image', models.CharField(blank=True, max_length=50, verbose_name='Modelo IA Imagem')),
                ('caption', models.TextField(verbose_name='Legenda')),
                ('hashtags', models.JSONField(default=list, verbose_name='Hashtags')),
                ('cta', models.CharField(blank=True, help_text='Call-to-action do post', max_length=160, verbose_name='CTA')),
                ('cta_requested', models.BooleanField(default=True, help_text='Usuário quer CTA no post', verbose_name='CTA Solicitado')),
                ('formats', models.JSONField(blank=True, default=list, help_text='Lista de formatos: ["feed", "story", "reels"]', verbose_name='Formatos')),
                ('is_carousel', models.BooleanField(default=False, help_text='Post é um carrossel (múltiplas imagens)', verbose_name='É Carrossel')),
                ('image_count', models.PositiveSmallIntegerField(default=1, help_text='Número de imagens no carrossel', verbose_name='Quantidade de Imagens')),
                ('slides_metadata', models.JSONField(blank=True, default=list, help_text='Dados estruturados de cada slide do carrossel', verbose_name='Metadados dos Slides')),
                ('revisions_remaining', models.PositiveSmallIntegerField(default=2, help_text='Número de revisões que o usuário ainda pode solicitar', verbose_name='Revisões Restantes')),
                ('thread_id', models.CharField(blank=True, help_text='ID do thread/job de processamento (N8N, GPT, etc)', max_length=160, verbose_name='Thread ID')),
                ('has_image', models.BooleanField(default=False, verbose_name='Tem Imagem')),
                ('image_s3_key', models.CharField(blank=True, max_length=500, verbose_name='Chave S3 Imagem')),
                ('image_s3_url', models.URLField(blank=True, max_length=1000, verbose_name='URL S3 Imagem')),
                ('image_prompt', models.TextField(blank=True, verbose_name='Prompt da Imagem')),
                ('image_width', models.IntegerField(blank=True, null=True, verbose_name='Largura')),
                ('image_height', models.IntegerField(blank=True, null=True, verbose_name='Altura')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('generating', 'Gerando'), ('pending', 'Pendente de Aprovação'), ('in_adjustment', 'Em Ajuste'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.area', verbose_name='Área')),
                ('organization', models.ForeignKey(blank=True, help_text='Organização à qual este post pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.organization', verbose_name='Organização')),
                ('pauta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='pautas.pauta', verbose_name='Pauta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='posts_post_created_183a3b_idx'), models.Index(fields=['user', '-created_at'], name='posts_post_user_id_b93466_idx'), models.Index(fields=['area', '-created_at'], name='posts_post_area_id_ed19fb_idx'), models.Index(fields=['status'], name='posts_post_status_79fb4e_idx'), models.Index(fields=['social_network'], name='posts_post_social__7cb638_idx')],
            },
        ),
    ]
