# Generated by Django 4.2.8 on 2026-02-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reference_images',
            field=models.JSONField(blank=True, default=list, help_text='URLs S3 das imagens de referência enviadas pelo usuário', verbose_name='Imagens de Referência'),
        ),
    ]
