# Generated by Django 4.2.8 on 2026-02-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_quotaadjustment_post'),
        ('posts', '0002_post_reference_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.area', verbose_name='Área'),
        ),
    ]
