# Generated by Django 4.2.8 on 2026-02-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pauta',
            name='rede_social',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn'), ('TWITTER', 'Twitter')], default='FACEBOOK', max_length=20, verbose_name='Rede Social'),
        ),
    ]
