# Generated by Django 4.2.8 on 2026-01-21 00:34

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_post_videoavatar_videoavatarstatus_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='Tagline')),
                ('plan_type', models.CharField(choices=[('pending', 'Aguardando Aprovação'), ('free', 'Gratuito'), ('basic', 'Básico'), ('premium', 'Premium'), ('custom', 'Personalizado')], default='free', help_text='Plano atual da organização', max_length=20, verbose_name='Tipo de Plano')),
                ('is_active', models.BooleanField(default=False, help_text='Organização aprovada e ativa. False = aguardando aprovação ou suspensa', verbose_name='Ativa')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovada em')),
                ('suspension_reason', models.CharField(blank=True, choices=[('', '(Nenhum - Organização Ativa)'), ('pending', 'Aguardando Aprovação'), ('payment', 'Pagamento Atrasado'), ('terms', 'Violação de Termos'), ('canceled', 'Cancelada pelo Cliente'), ('other', 'Outro Motivo')], default='pending', help_text='Motivo da suspensão/inativação (vazio = ativa)', max_length=20, verbose_name='Motivo de Suspensão')),
                ('quota_pautas_dia', models.PositiveIntegerField(default=3, help_text='Limite de pautas por dia (0 = bloqueado)', verbose_name='Quota Pautas/Dia')),
                ('quota_posts_dia', models.PositiveIntegerField(default=3, help_text='Limite de posts por dia (0 = bloqueado)', verbose_name='Quota Posts/Dia')),
                ('quota_posts_mes', models.PositiveIntegerField(default=15, help_text='Limite de posts por mês (0 = ilimitado)', verbose_name='Quota Posts/Mês')),
                ('quota_videos_dia', models.PositiveSmallIntegerField(default=2, help_text='Máximo de vídeos avatar por dia', verbose_name='Quota Vídeos/Dia')),
                ('quota_videos_mes', models.PositiveSmallIntegerField(default=5, help_text='Máximo de vídeos avatar por mês (ciclo de billing)', verbose_name='Quota Vídeos/Mês')),
                ('videos_avatar_enabled', models.BooleanField(default=False, help_text='Empresa autorizada a criar vídeos avatar', verbose_name='Vídeos Avatar Habilitados')),
                ('billing_cycle_day', models.PositiveSmallIntegerField(default=1, help_text='Dia do mês que reseta a quota mensal (1-31). Ex: 15 = todo dia 15', verbose_name='Dia do Ciclo de Faturamento')),
                ('internal_notes', models.TextField(blank=True, help_text='Notas internas da equipe (não visível para cliente)', verbose_name='Notas Internas')),
                ('alert_80_enabled', models.BooleanField(default=True, help_text='Enviar alerta quando atingir 80% da quota', verbose_name='Alertas 80% Habilitados')),
                ('alert_100_enabled', models.BooleanField(default=True, help_text='Enviar alerta quando atingir 100% da quota', verbose_name='Alertas 100% Habilitados')),
                ('alert_email', models.EmailField(blank=True, help_text='Email para receber alertas (deixe vazio para usar email do owner)', max_length=254, verbose_name='Email de Alertas')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprovada por')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PautaAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('requested', 'Solicitado'), ('webhook_sent', 'Webhook Enviado'), ('webhook_failed', 'Webhook Falhou'), ('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=40, verbose_name='Ação')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pauta_audit_logs', to='core.organization', verbose_name='Organização')),
                ('pauta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='content.pauta', verbose_name='Pauta')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria de Pauta',
                'verbose_name_plural': 'Logs de Auditoria de Pautas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='QuotaAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('pauta_daily', 'Pauta (Diária)'), ('post_daily', 'Post (Diária)'), ('post_monthly', 'Post (Mensal)')], help_text='Tipo de quota ajustada', max_length=20, verbose_name='Tipo de Recurso')),
                ('adjustment_type', models.CharField(choices=[('refund', 'Devolução (Erro/Falha)'), ('bonus', 'Bônus (Promocional)'), ('correction', 'Correção Manual'), ('plan_change', 'Mudança de Plano')], help_text='Motivo do ajuste', max_length=20, verbose_name='Tipo de Ajuste')),
                ('amount', models.IntegerField(help_text='Quantidade ajustada (positivo=adicionar, negativo=remover)', verbose_name='Quantidade')),
                ('reason', models.TextField(help_text='Motivo detalhado do ajuste', verbose_name='Motivo')),
                ('adjusted_by', models.ForeignKey(help_text='Usuário que fez o ajuste', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quota_adjustments_made', to=settings.AUTH_USER_MODEL, verbose_name='Ajustado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_adjustments', to='core.organization', verbose_name='Organização')),
                ('pauta_audit_log', models.ForeignKey(blank=True, help_text='Referência ao audit log da pauta (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quota_adjustments', to='core.pautaauditlog', verbose_name='Log de Auditoria da Pauta')),
                ('post', models.ForeignKey(blank=True, help_text='Referência ao post (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quota_adjustments', to='content.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Ajuste de Quota',
                'verbose_name_plural': 'Ajustes de Quotas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='area',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organização à qual a área pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organização à qual o usuário pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.organization', verbose_name='Organização'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('organization', 'name')},
        ),
        migrations.CreateModel(
            name='QuotaUsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='Data')),
                ('pautas_requested', models.PositiveIntegerField(default=0, help_text='Pautas solicitadas hoje', verbose_name='Pautas Solicitadas')),
                ('posts_created', models.PositiveIntegerField(default=0, help_text='Posts criados hoje', verbose_name='Posts Criados')),
                ('videos_created', models.PositiveIntegerField(default=0, help_text='Vídeos avatar criados hoje', verbose_name='Vídeos Criados')),
                ('pautas_adjustments', models.IntegerField(default=0, help_text='Ajustes de pautas (+/-)', verbose_name='Ajustes de Pautas')),
                ('posts_adjustments', models.IntegerField(default=0, help_text='Ajustes de posts (+/-)', verbose_name='Ajustes de Posts')),
                ('videos_adjustments', models.IntegerField(default=0, help_text='Ajustes de vídeos (+/-)', verbose_name='Ajustes de Vídeos')),
                ('cost_usd', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Custo total em USD das operações deste dia', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Custo USD')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_usage_daily', to='core.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Uso Diário de Quota',
                'verbose_name_plural': 'Uso Diário de Quotas',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organization', '-date'], name='core_quotau_organiz_6fc306_idx')],
                'unique_together': {('organization', 'date')},
            },
        ),
        migrations.CreateModel(
            name='QuotaAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('80', '80% da Quota'), ('100', '100% da Quota (Limite Atingido)')], max_length=3, verbose_name='Tipo de Alerta')),
                ('resource_type', models.CharField(choices=[('pauta_daily', 'Pauta (Diária)'), ('post_daily', 'Post (Diária)'), ('post_monthly', 'Post (Mensal)'), ('video_daily', 'Vídeo (Diária)'), ('video_monthly', 'Vídeo (Mensal)')], max_length=20, verbose_name='Tipo de Recurso')),
                ('date', models.DateField(db_index=True, help_text='Data em que o alerta foi disparado', verbose_name='Data')),
                ('sent_to', models.EmailField(help_text='Email para onde o alerta foi enviado', max_length=254, verbose_name='Enviado Para')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_alerts', to='core.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Alerta de Quota',
                'verbose_name_plural': 'Alertas de Quotas',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['organization', '-date'], name='core_quotaa_organiz_81b4fb_idx'), models.Index(fields=['alert_type', '-date'], name='core_quotaa_alert_t_ab3eb9_idx')],
                'unique_together': {('organization', 'alert_type', 'resource_type', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='pautaauditlog',
            index=models.Index(fields=['organization', '-created_at'], name='core_pautaa_organiz_77b1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='pautaauditlog',
            index=models.Index(fields=['action', '-created_at'], name='core_pautaa_action_35b1ef_idx'),
        ),
    ]
