# Generated by Django 4.2.8 on 2026-01-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_pautaauditlog_alter_area_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsageLimit',
        ),
    ]
