# Generated by Django 4.2.8 on 2026-01-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usagelimit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='area',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.RemoveField(
            model_name='area',
            name='organization',
        ),
    ]
