# Generated by Django 4.2.8 on 2026-01-26 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_organization_from_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_type', models.CharField(choices=[('pending', 'Aguardando Aprovação'), ('free', 'Gratuito'), ('basic', 'Básico'), ('premium', 'Premium'), ('custom', 'Personalizado')], max_length=20, unique=True, verbose_name='Tipo de Plano')),
                ('name', models.CharField(help_text='Ex: Plano Gratuito, Plano Básico', max_length=100, verbose_name='Nome do Plano')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('quota_pautas_dia', models.PositiveIntegerField(default=3, help_text='Limite de pautas que podem ser criadas por dia', verbose_name='Pautas por Dia')),
                ('quota_posts_dia', models.PositiveIntegerField(default=3, help_text='Limite de posts que podem ser criados por dia', verbose_name='Posts por Dia')),
                ('quota_posts_mes', models.PositiveIntegerField(default=15, help_text='Limite de posts que podem ser criados por mês', verbose_name='Posts por Mês')),
                ('quota_videos_dia', models.PositiveSmallIntegerField(default=0, help_text='Limite de vídeos avatar por dia (0 = desabilitado)', verbose_name='Vídeos Avatar por Dia')),
                ('quota_videos_mes', models.PositiveSmallIntegerField(default=0, help_text='Limite de vídeos avatar por mês (0 = desabilitado)', verbose_name='Vídeos Avatar por Mês')),
                ('videos_avatar_enabled', models.BooleanField(default=False, help_text='Se marcado, permite criação de vídeos avatar', verbose_name='Vídeos Avatar Habilitados')),
                ('is_active', models.BooleanField(default=True, help_text='Plano disponível para uso', verbose_name='Ativo')),
                ('is_default', models.BooleanField(default=False, help_text='Plano aplicado por padrão em novas aprovações', verbose_name='Padrão')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Ordem de exibição no admin (menor = primeiro)', verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Template de Plano',
                'verbose_name_plural': 'Templates de Planos',
                'ordering': ['display_order', 'plan_type'],
            },
        ),
    ]
