# Generated by Django - Data Migration

from django.db import migrations


def create_default_plan_templates(apps, schema_editor):
    """Cria templates de plano padrão"""
    PlanTemplate = apps.get_model('core', 'PlanTemplate')
    
    templates = [
        {
            'plan_type': 'free',
            'name': 'Plano Gratuito',
            'description': 'Plano básico gratuito para teste da plataforma',
            'quota_pautas_dia': 3,
            'quota_posts_dia': 3,
            'quota_posts_mes': 15,
            'quota_videos_dia': 0,
            'quota_videos_mes': 0,
            'videos_avatar_enabled': False,
            'is_active': True,
            'is_default': True,
            'display_order': 1
        },
        {
            'plan_type': 'basic',
            'name': 'Plano Básico',
            'description': 'Plano básico com mais recursos e vídeos avatar',
            'quota_pautas_dia': 5,
            'quota_posts_dia': 5,
            'quota_posts_mes': 30,
            'quota_videos_dia': 1,
            'quota_videos_mes': 3,
            'videos_avatar_enabled': True,
            'is_active': True,
            'is_default': False,
            'display_order': 2
        },
        {
            'plan_type': 'premium',
            'name': 'Plano Premium',
            'description': 'Plano completo com todos os recursos e limites expandidos',
            'quota_pautas_dia': 10,
            'quota_posts_dia': 10,
            'quota_posts_mes': 60,
            'quota_videos_dia': 3,
            'quota_videos_mes': 10,
            'videos_avatar_enabled': True,
            'is_active': True,
            'is_default': False,
            'display_order': 3
        }
    ]
    
    for template_data in templates:
        PlanTemplate.objects.create(**template_data)


def reverse_populate(apps, schema_editor):
    """Remove templates criados"""
    PlanTemplate = apps.get_model('core', 'PlanTemplate')
    PlanTemplate.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_plan_template'),
    ]

    operations = [
        migrations.RunPython(create_default_plan_templates, reverse_populate),
    ]
