# Generated by Django 4.2.8 on 2026-02-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('core', '0007_organization_email_marketing_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotaadjustment',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Referência ao post (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quota_adjustments', to='posts.post', verbose_name='Post'),
        ),
    ]
